// <auto-generated />
namespace SNAuthentication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FirstNameLastNameadd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FirstNameLastNameadd));
        
        string IMigrationMetadata.Id
        {
            get { return "201612122206258_First Name Last Name add"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
