// <auto-generated />
namespace SNAuthentication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _3TermsAddedBoolean : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_3TermsAddedBoolean));
        
        string IMigrationMetadata.Id
        {
            get { return "201701151456040_3TermsAddedBoolean"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
